name: chat_kare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  logger: ^2.6.2
  dartz: ^0.10.1
  get: ^4.7.3
  go_router: ^17.1.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_database: ^12.1.2
  firebase_messaging: ^16.1.1
  equatable: ^2.0.8
  flutter_contacts: ^1.1.9+2
  google_fonts: ^8.0.0
  flutter_local_notifications: ^20.0.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
